import { expect, test } from 'bun:test'
import { spawn } from 'node:child_process'
import { existsSync, promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function runCli(cwd: string, args: string[]): Promise<string> {
	return new Promise((resolve, reject) => {
		const bin = path.resolve(__dirname, '../src/cli/index.ts')
		const proc = spawn(process.execPath, [bin, ...args], {
			cwd,
			stdio: 'pipe',
		})
		let out = ''
		proc.stdout.on('data', (d) => {
			out += d.toString()
		})
		proc.stderr.on('data', (d) => {
			out += d.toString()
		})
		proc.on('exit', (code) => {
			if (code === 0) resolve(out.trim())
			else reject(new Error(`exit ${code}: ${out}`))
		})
	})
}

test('cli compose generates AGENTS.md', async () => {
	const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'agents-md-cli-'))
	await fs.writeFile(path.join(tmp, 'a.agents.md'), 'Hello')
	await runCli(tmp, ['compose'])
	const out = await fs.readFile(path.join(tmp, 'AGENTS.md'), 'utf8')
	expect(out).toContain('Hello')
})

test('cli init scaffolds config and migrates AGENTS.md', async () => {
	const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'agents-md-init-'))
	await fs.writeFile(path.join(tmp, 'AGENTS.md'), 'Legacy')
	const output = await runCli(tmp, ['init'])
	const fragment = await fs.readFile(
		path.join(tmp, 'project.agents.md'),
		'utf8',
	)
	expect(fragment).toContain('Legacy')
	const config = await fs.readFile(
		path.join(tmp, 'agents-md.config.ts'),
		'utf8',
	)
	expect(config).toBe(
		"import type { AgentsMdConfig } from 'agents-md'\n\n" +
			'export default {\n' +
			'  include: [\n' +
			"    '**/agents-md/**/*.md',\n" +
			"    '**/*.agents.md',\n" +
			'  ],\n' +
			'} satisfies AgentsMdConfig\n',
	)
	const generated = await fs.readFile(path.join(tmp, 'AGENTS.md'), 'utf8')
	expect(generated).toContain('Legacy')
	expect(output).toMatch(/created agents-md.config.ts/)
})

test('cli init creates AGENTS.md when missing', async () => {
	const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'agents-md-init-empty-'))
	const out = await runCli(tmp, ['init'])
	expect(out).toContain('created agents-md.config.ts')
	const generated = await fs.readFile(path.join(tmp, 'AGENTS.md'), 'utf8')
	expect(generated).toBe(
		'<!-- Generated by agents-md: DO NOT EDIT DIRECTLY. Edit *.agents.md fragments instead. Higher priority fragments appear first and win conflicts. -->\n',
	)
})

test('cli init skips when config exists', async () => {
	const tmp = await fs.mkdtemp(
		path.join(os.tmpdir(), 'agents-md-init-skip-config-'),
	)
	await fs.writeFile(
		path.join(tmp, 'agents-md.config.ts'),
		'export default {}\n',
	)
	const out = await runCli(tmp, ['init'])
	expect(out).toContain('already initialized')
	expect(existsSync(path.join(tmp, 'project.agents.md'))).toBe(false)
})

test('cli init skips when generated AGENTS.md exists', async () => {
	const tmp = await fs.mkdtemp(
		path.join(os.tmpdir(), 'agents-md-init-skip-agents-'),
	)
	await fs.writeFile(
		path.join(tmp, 'AGENTS.md'),
		'<!-- Generated by agents-md: DO NOT EDIT DIRECTLY. -->\n',
	)
	const out = await runCli(tmp, ['init'])
	expect(out).toContain('already initialized')
	expect(existsSync(path.join(tmp, 'agents-md.config.ts'))).toBe(false)
})

test('cli report outputs json', async () => {
	const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'agents-md-report-'))
	await fs.writeFile(path.join(tmp, 'a.agents.md'), 'A')
	const out = await runCli(tmp, ['report', '--json'])
	const data = JSON.parse(out)
	expect(data.outputs[0].path).toBe('AGENTS.md')
	expect(data.outputs[0].chars).toBeGreaterThan(0)
	expect(data.totals.chars).toBeGreaterThan(0)
})

test('cli report prints friendly output', async () => {
	const tmp = await fs.mkdtemp(
		path.join(os.tmpdir(), 'agents-md-report-human-'),
	)
	await fs.writeFile(path.join(tmp, 'a.agents.md'), 'A')
	const out = await runCli(tmp, ['report'])
	expect(out).toContain('AGENTS.md (root) -')
	expect(out).toMatch(/k chars/)
	expect(out).toContain('Totals: 1 AGENTS.md files')
})

test('cli compose respects config include globs', async () => {
	const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'agents-md-cli-config-'))
	await fs.mkdir(path.join(tmp, 'docs'), { recursive: true })
	await fs.writeFile(path.join(tmp, 'docs/design.md'), 'Design')
	await fs.writeFile(
		path.join(tmp, 'agents-md.config.ts'),
		"import type { AgentsMdConfig } from 'agents-md'\n\n" +
			'export default {\n' +
			"  include: ['**/docs/**/*.md'],\n" +
			'} satisfies AgentsMdConfig\n',
	)
	await runCli(tmp, ['compose'])
	const out = await fs.readFile(path.join(tmp, 'AGENTS.md'), 'utf8')
	expect(out).toContain('Design')
})
