import { existsSync, promises as fs } from 'node:fs'
import path from 'node:path'
import fg from 'fast-glob'
import { BANNER, compose } from './compose'
import { createAgentsMdPrefix } from './logger'
import type { AgentsMdConfig, Output } from './types'

export async function init(
	config: AgentsMdConfig & { cwd?: string } = {},
): Promise<Output[]> {
	const cwd = config.cwd ?? process.cwd()
	const configNames = [
		'agents-md.config.ts',
		'agents-md.config.mjs',
		'agents-md.config.js',
	]
	if (configNames.some((n) => existsSync(path.join(cwd, n)))) {
		console.log(
			`${createAgentsMdPrefix()}: ✅ Already initialized! Use \`agents-md compose\` to regenerate files.`,
		)
		return []
	}

	const existing = await fg('**/AGENTS.md', { cwd })
	for (const rel of existing) {
		const full = path.join(cwd, rel)
		const content = await fs.readFile(full, 'utf8')
		if (content.includes('Generated by agents-md')) {
			console.log(
				'✅ Already initialized! Use `agents-md compose` to regenerate files.',
			)
			return []
		}
	}

	const project = 'project'
	const fragment = path.join(cwd, `${project}.agents.md`)

	const claude = path.join(cwd, 'CLAUDE.md')
	const rootAgents = path.join(cwd, 'AGENTS.md')

	if (existsSync(claude) && !existsSync(fragment)) {
		await fs.rename(claude, fragment)
		await fs.writeFile(claude, '@AGENTS.md\n')
		console.log(
			`${createAgentsMdPrefix()}: 📝 Moved CLAUDE.md → ${project}.agents.md`,
		)
	} else if (existsSync(rootAgents) && !existsSync(fragment)) {
		const content = await fs.readFile(rootAgents, 'utf8')
		await fs.writeFile(fragment, content)
		await fs.unlink(rootAgents)
		console.log(
			`${createAgentsMdPrefix()}: 📝 Moved AGENTS.md → ${project}.agents.md`,
		)
	}

	const configPath = path.join(cwd, 'agents-md.config.ts')
	const body =
		"import type { AgentsMdConfig } from 'agents-md'\n\n" +
		'export default {\n' +
		'  include: [\n' +
		"    '**/agents-md/**/*.md',\n" +
		"    '**/*.agents.md',\n" +
		'  ],\n' +
		'} satisfies AgentsMdConfig\n'
	await fs.writeFile(configPath, body)
	console.log(`${createAgentsMdPrefix()}: ⚙️  Created agents-md.config.ts`)

	if (!existsSync(rootAgents)) {
		await fs.writeFile(rootAgents, `${BANNER}\n`)
	}

	return compose({ ...config, cwd })
}
